#include<stdio.h>
#include "capitals.h"

char neCapitals[9][20] = { "Augusta",
"Trenton",
"Concord",
"Hartford",
"Montpelier",
"Boston",
"Albany",
"Harrisburg",
"Providence" };

char mwCapitals[12][20] = { "Columbus",
"Indianapolis",
"Springfield",
"Jefferson City",
"Topeka",
"Lincoln",
"Des Moines",
"Milwaukee",
"St Paul",
"Bismark",
"Pierre",
"Lansing" };

char sCapitals[17][25] = { "Dover",
"Annapolis",
"Richmond",
"Charleston",
"Frankfort",
"Raleigh",
"Columbia",
"Nashville",
"Atlanta",
"Tallahassee",
"Montgomery",
"Jackson",
"Little Rock",
"Baton Rouge",
"Oklahoma City",
"Austin",
"Disctrict of Columbia"};

char wCapitals[13][20] = { "Olympia",
"Salem",
"Boise",
"Helena",
"Cheyenne",
"Sacramento",
"Carson City",
"Salt Lake City",
"Denver",
"Phoenix",
"Santa Fe",
"Juneau",
"Honolulu" };