#include <stdio.h>
#include "states.h"

char neStates[9][20] = { "Maine",
"New Jersey",
"New Hampshire",
"Connecticut",
"Vermont",
"Massachusetts",
"New York",
"Pennsylvania",
"Rhode Island" };

char mwStates[12][20] = { "Ohio",
"Indiana",
"Illinois",
"Missouri",
"Kansas",
"Nebraska",
"Iowa",
"Wisconsin",
"Minnesota",
"North Dakota",
"South Dakota",
"Michigan" };

char southStates[17][25] = { "Delaware",
"Maryland",
"Virginia",
"West Virginia",
"Kentucky",
"North Carolina",
"South Carolina",
"Tennessee",
"Georgia",
"Florida",
"Alabama",
"Mississippi",
"Arkansas",
"Louisiana",
"Oklahoma",
"Texas",
"Disctrict of Columbia" };

char westernStates[13][20] = { "Washington",
"Oregon",
"Idaho",
"Montana",
"Wyoming",
"California",
"Nevada",
"Utah",
"Colorado",
"Arizona",
"New Mexico",
"Alaska",
"Hawaii" };